// SPDX-FileCopyrightText: 2025 SternXD
// SPDX-License-Identifier: AGPL-3.0

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    'faq',
    {
      type: 'category',
      label: 'Xbox Setup',
      items: [{type: 'autogenerated', dirName: 'xbox-setup'}],
    },
    {
      type: 'category',
      label: 'Emulation Guides',
      items: [{type: 'autogenerated', dirName: 'emulation'}],
    },
    {
      type: 'category',
      label: 'Experimental Ports',
      items: [{type: 'autogenerated', dirName: 'experimental'}],
    },
    {
      type: 'category',
      label: 'Frontends',
      items: [{type: 'autogenerated', dirName: 'frontends'}],
    },
    {
      type: 'category',
      label: 'Native ports & engines',
      items: [{type: 'autogenerated', dirName: 'ports'}],
    },
    {
      type: 'category',
      label: 'Development Guides',
      items: [{type: 'autogenerated', dirName: 'development'}],
    },
    {
      type: 'category',
      label: 'Helpful Links',
      items: [{type: 'autogenerated', dirName: 'helpful-links'}],
    },
  ],
};

export default sidebars;
